### ISSUE TITLE
How does auto mocking with TinyIoc work?

### ISSUE THREAD

**Issue by kevinkuszyk** [ChillBDD/Chill#29]
First up, this looks like a great library - I think I'll be using it on my next project.

In the meantime I was wondering how you do auto mocking with `TinyIoc`?  I've looked through the code, but I can't see how you wire it up.

Thanks in advance.

**Comment by Erwinvandervalk** [comment]
Hi Kevin, 

It doesn't yet. I made a design error where the extensions bundle both the mocking framework and the container type. Later I was using Chill a lot without mocking, so I figured, I'd add TinyIOC to it. But now I need a clean way to 'just' specify the mocking library. 

Regards,
Erwin
