### ISSUE TITLE
Specs with fire-and-forget tasks in sync-version of Given dead-lock

### ISSUE THREAD

**Issue by tomachristian** [ChillBDD/Chill#77]
For the async version of `Given`, Chill has the `Task`s execute with the `ExecuteInDefaultSynchronizationContext()`, but for the sync version of `Given` Chill does not do this.

If a Task is "fired-and-forgotten" inside the sync version of `Given`: `_ = taskRunner.RunTaskAsync()`, the `await`s inside that Task would still run with the xUnit `SynchronizationContext` which can cause dead-locks (in particular when the next When is async and blocks because Chill does `.GetAwaiter().GetResult()` on the delegate).

Consider using `ExecuteInDefaultSynchronizationContext` for the sync versions of `Given` and `When` to solve this.

**Comment by dennisdoomen** [comment]
As far as I can see, this is exactly what 4.0 beta 1 is doing (accidentally). See https://github.com/ChillBDD/Chill/blob/develop/Src/Chill/TaskExtensions.cs#L34. Since 4.0 does not compile for .NET 4.5, only the `#else` block is run.

**Comment by tomachristian** [comment]
Yes, it is removing the `SynchronizationContext.Current` for both `Given(Func<Task>)` and `When(Func<Task>)`, our request is for it do do the same for `Given(Action)` and `When(Action)`.

**Comment by dennisdoomen** [comment]
Alright. I'll probably use https://blogs.msdn.microsoft.com/benwilli/2017/02/09/an-alternative-to-configureawaitfalse-everywhere/.
